AWSTemplateFormatVersion: "2010-09-09"
Description: "MAP Tagger Solution - Cross Account Role - (uksb-kzxy2tzxlf)"
Parameters:
  RoleARN:
      Type: String
      Description: IAM ARN Role for Central Account
Resources:
    IAMPolicyMapTaggerSolution:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            ManagedPolicyName: !Join [ "-", ["policy-map-tagger-solution", !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
            PolicyDocument: !Sub |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Action": [
                        "apigateway:GET",
                        "apigateway:PATCH",
                        "apigateway:PUT",
                        "apigateway:DELETE",
                        "apigateway:POST",
                        "backup:ListBackupVaults",
                        "backup:ListBackupPlans",
                        "backup:ListTags",
                        "backup:TagResource",
                        "dynamodb:ListTables",
                        "dynamodb:Describe*",
                        "dynamodb:TagResource",
                        "dynamodb:ListTagsOfResource",
                        "dax:DescribeClusters",
                        "dynamodb:ListBackups",
                        "ec2:Describe*",
                        "ec2:CreateTags",
                        "ec2:DeleteTags",
                        "ec2:DescribeVolumes",
                        "ec2:DescribeSnapshots",
                        "ec2:DescribeTransitGateways",
                        "ec2:DescribeTransitGatewayAttachments",
                        "ec2:DescribeTags",
                        "ec2:CreateTags",
                        "ecr:DescribeRepositories",
                        "ecr:ListTagsForResource",
                        "ecr:TagResource",
                        "ecs:ListClusters",
                        "ecs:DescribeClusters",
                        "ecs:ListTagsForResource",
                        "ecs:TagResource",
                        "eks:ListClusters",
                        "eks:ListTagsForResource",
                        "eks:TagResource",
                        "elasticfilesystem:Describe*",
                        "elasticfilesystem:CreateTags",
                        "elasticfilesystem:ListTagsForResource",
                        "elasticloadbalancing:AddTags",
                        "elasticloadbalancing:Describe*",
                        "elasticmapreduce:DescribeCluster",
                        "elasticmapreduce:ListClusters",
                        "elasticmapreduce:AddTags",
                        "fsx:TagResource",
                        "fsx:DescribeFileSystems",
                        "fsx:ListTagsForResource",
                        "fsx:DescribeBackups",
                        "lambda:List*",
                        "lambda:Get*",
                        "lambda:TagResource",
                        "logs:CreateLogGroup",
                        "logs:CreateLogStream",
                        "logs:PutLogEvents",
                        "logs:DescribeLogGroups",
                        "logs:DescribeLogStreams",
                        "redshift:CreateTags",
                        "redshift:Describe*",
                        "rds:ListTagsForResource",
                        "rds:Describe*",
                        "rds:DescribeDBInstances",
                        "rds:AddTagsToResource",
                        "s3:Get*",
                        "s3:List*",
                        "s3:PutBucketTagging",
                        "tag:Get*",
                        "tag:TagResources",
                        "transfer:ListServers",
                        "transfer:ListTagsForResource",
                        "transfer:TagResource",
                        "workspaces:DescribeWorkspaces",
                        "workspaces:CreateTags",
                        "rds:RemoveTagsFromResource",
                        "elasticloadbalancing:RemoveTags",
                        "elasticfilesystem:DeleteTags",
                        "fsx:UntagResource",
                        "dynamodb:UntagResource",
                        "lambda:UntagResource",
                        "backup:UntagResource",
                        "ecr:UntagResource",
                        "eks:UntagResource",
                        "eks:DescribeCluster",
                        "ecs:UntagResource",
                        "elasticmapreduce:RemoveTags",
                        "transfer:DescribeServer",
                        "transfer:UntagResource",
                        "elasticache:DescribeCacheSubnetGroups",
                        "elasticache:DescribeSnapshots",
                        "elasticache:DescribeCacheClusters",
                        "elasticache:DescribeReplicationGroups",
                        "elasticache:DescribeCacheParameterGroups",
                        "timestream:DescribeEndpoints",
                        "timestream:ListDatabases",
                        "timestream:ListTables",
                        "memorydb:DescribeClusters",
                        "memorydb:DescribeSnapshots",
                        "apigateway:PATCH",
                        "elasticfilesystem:TagResource",
                        "elasticfilesystem:UnTagResource",
                        "elasticache:AddTagsToResource",
                        "elasticache:RemoveTagsFromResource",
                        "memorydb:TagResource",
                        "memorydb:UnTagResource",
                        "timestream:TagResource",
                        "timestream:UnTagResource",
                        "timestream:ListTagsForResource",
                        "workspaces:DeleteTags",
                        "athena:ListDataCatalogs",
                        "athena:ListCapacityReservations",
                        "athena:ListTagsForResource",
                        "athena:TagResource",
                        "athena:UntagResource",
                        "cognito-identity:ListIdentityPools",
                        "cognito-identity:DescribeIdentityPool",
                        "cognito-identity:ListTagsForResource",
                        "cognito-identity:TagResource",
                        "cognito-identity:UntagResource",
                        "cognito-idp:ListUserPools",
                        "cognito-idp:DescribeUserPool",
                        "cognito-idp:DescribeUserPoolDomain",
                        "cognito-idp:ListTagsForResource",
                        "cognito-idp:TagResource",
                        "cognito-idp:UntagResource",
                        "ds:DescribeDirectories",
                        "ds:ListTagsForResource",
                        "ds:AddTagsToResource",
                        "ds:RemoveTagsFromResource",
                        "ec2:CreateTags",
                        "ec2:DeleteTags",
                        "ec2:DescribeTags",
                        "glacier:ListVaults",
                        "glacier:DescribeVault",
                        "glacier:ListTagsForVault",
                        "glacier:AddTagsToVault",
                        "glacier:RemoveTagsFromVault",
                        "glue:GetConnections",
                        "glue:GetConnection",
                        "glue:GetDatabases",
                        "glue:GetDatabase",
                        "glue:GetCrawlers",
                        "glue:GetCrawler",
                        "glue:ListSessions",
                        "glue:GetSession",
                        "glue:GetDevEndpoints",
                        "glue:GetDevEndpoint",
                        "glue:GetJobs",
                        "glue:GetJob",
                        "glue:GetTriggers",
                        "glue:GetTrigger",
                        "glue:ListWorkflows",
                        "glue:GetWorkflow",
                        "glue:ListBlueprints",
                        "glue:GetBlueprint",
                        "glue:GetMLTransforms",
                        "glue:GetMLTransform",
                        "glue:ListDataQualityRulesets",
                        "glue:GetDataQualityRuleset",
                        "glue:ListRegistries",
                        "glue:GetRegistry",
                        "glue:ListSchemas",
                        "glue:GetSchema",
                        "glue:GetTags",
                        "glue:TagResource",
                        "glue:UntagResource",
                        "kms:ListKeys",
                        "kms:ListAliases",
                        "kms:DescribeKey",
                        "kms:ListResourceTags",
                        "kms:TagResource",
                        "kms:UntagResource",
                        "medical-imaging:ListDatastores",
                        "medical-imaging:GetDatastore",
                        "medical-imaging:ListTagsForResource",
                        "medical-imaging:TagResource",
                        "medical-imaging:UntagResource",
                        "redshift:DescribeClusters",
                        "redshift:DescribeClusterSnapshots",
                        "redshift:DescribeClusterSubnetGroups",
                        "redshift:DescribeClusterParameterGroups",
                        "redshift:DescribeScheduledActions",
                        "redshift:DescribeTags",
                        "redshift:CreateTags",
                        "redshift:DeleteTags",
                        "redshift-serverless:ListWorkgroups",
                        "redshift-serverless:GetWorkgroup",
                        "redshift-serverless:ListNamespaces",
                        "redshift-serverless:GetNamespace",
                        "redshift-serverless:ListSnapshots",
                        "redshift-serverless:GetSnapshot",
                        "redshift-serverless:ListRecoveryPoints",
                        "redshift-serverless:GetRecoveryPoint",
                        "redshift-serverless:ListTagsForResource",
                        "redshift-serverless:TagResource",
                        "redshift-serverless:UntagResource",
                        "route53:ListHostedZones",
                        "route53:ListHealthChecks",
                        "route53:ListTagsForResource",
                        "route53:ChangeTagsForResource",
                        "route53resolver:ListResolverEndpoints",
                        "route53resolver:ListResolverRules",
                        "route53resolver:ListResolverQueryLogConfigs",
                        "route53resolver:ListFirewallDomainLists",
                        "route53resolver:ListFirewallRuleGroups",
                        "route53resolver:ListFirewallRuleGroupAssociations",
                        "route53resolver:ListTagsForResource",
                        "route53resolver:TagResource",
                        "route53resolver:UntagResource",
                        "route53-recovery-control-config:ListClusters",
                        "route53-recovery-control-config:ListControlPanels",
                        "route53-recovery-control-config:ListRoutingControls",
                        "route53-recovery-control-config:ListSafetyRules",
                        "route53-recovery-control-config:ListTagsForResource",
                        "route53-recovery-control-config:TagResource",
                        "route53-recovery-control-config:UntagResource",
                        "route53-recovery-readiness:ListCells",
                        "route53-recovery-readiness:ListReadinessChecks",
                        "route53-recovery-readiness:ListRecoveryGroups",
                        "route53-recovery-readiness:ListResourceSets",
                        "route53-recovery-readiness:ListTagsForResource",
                        "route53-recovery-readiness:TagResource",
                        "route53-recovery-readiness:UntagResource",
                        "route53domains:ListDomains",
                        "route53domains:ListTagsForDomain",
                        "route53domains:UpdateTagsForDomain",
                        "route53profiles:ListProfiles",
                        "route53profiles:ListProfileAssociations",
                        "route53profiles:ListTagsForResource",
                        "route53profiles:TagResource",
                        "route53profiles:UntagResource",
                        "secretsmanager:ListSecrets",
                        "secretsmanager:DescribeSecret",
                        "secretsmanager:TagResource",
                        "secretsmanager:UntagResource",
                        "securityhub:DescribeHub",
                        "securityhub:GetInsights",
                        "securityhub:GetEnabledStandards",
                        "securityhub:ListTagsForResource",
                        "securityhub:TagResource",
                        "securityhub:UntagResource",
                        "sns:ListTopics",
                        "sns:GetTopicAttributes",
                        "sns:ListTagsForResource",
                        "sns:TagResource",
                        "sns:UntagResource",
                        "sqs:ListQueues",
                        "sqs:GetQueueAttributes",
                        "sqs:ListQueueTags",
                        "sqs:TagQueue",
                        "sqs:UntagQueue",
                        "ssm:DescribeParameters",
                        "ssm:ListDocuments",
                        "ssm:DescribeMaintenanceWindows",
                        "ssm:DescribePatchBaselines",
                        "ssm:ListTagsForResource",
                        "ssm:AddTagsToResource",
                        "ssm:RemoveTagsFromResource",
                        "ssm-contacts:ListContacts",
                        "ssm-contacts:GetContact",
                        "ssm-contacts:ListTagsForResource",
                        "ssm-contacts:TagResource",
                        "ssm-contacts:UntagResource",
                        "ssm-incidents:ListResponsePlans",
                        "ssm-incidents:GetResponsePlan",
                        "ssm-incidents:ListIncidents",
                        "ssm-incidents:GetIncidentRecord",
                        "ssm-incidents:ListReplicationSets",
                        "ssm-incidents:GetReplicationSet",
                        "ssm-incidents:ListTagsForResource",
                        "ssm-incidents:TagResource",
                        "ssm-incidents:UntagResource",
                        "states:ListStateMachines",
                        "states:DescribeStateMachine",
                        "states:ListActivities",
                        "states:DescribeActivity",
                        "states:ListTagsForResource",
                        "states:TagResource",
                        "states:UntagResource"
                      ],
                      "Resource": "*"
                    }
                  ]
                }
                
    IAMRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/"
            RoleName: "IAMChildRoleTaggerSolution"
            AssumeRolePolicyDocument: !Sub |
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {
                                "AWS": "${RoleARN}"
                            },
                            "Action": "sts:AssumeRole"
                        }
                    ]
                }
            MaxSessionDuration: 3600
            ManagedPolicyArns:
                - !Ref IAMPolicyMapTaggerSolution
    
    